Stack-to-the-Future/atelier

- README.md
Added Greg's information to Contact section.
> Updated Greg's links in Contact section.

- README.md
#updated contact links
Thomas's contact links are now up to date.
> fixed: added appropriate links in 'contact'

- README.md
Faycal's Changed Linkedin & Github info
> contact changes

- README.md
1. Removed unused link in Greg's section
1. Changed Ming's twitter link to github link
1. Adjusted Faycal's GITHUB link to GitHub
> docs: adjusted links in README

- README.md
- Removed the word My from My Portfolio
> add: changed README.md

- README.md
changed Fayçal's name to proper spelling
>  Faycal name changed to Fayçal

- README.md
fixed: changed url for Thomas's linked-in
> updated linked-in

- client/src/components/App.jsx
- client/src/components/RelatedProducts.jsx
Added my env file and a  RelatedProducts component to App.jsx
>  env file added and RelatedProducts comp created

- .gitignore
- package.json
- tests/initial.test.js
- Added coverage to list of folders to ignore
- Added jest dependencies 
- Added initial test
> Jest config

- client/src/components/App.jsx
- package.json
Imported RatingsAndReviews 
Moved the URL to the .env folder
API is connected and a target product was selected
> established API connection

- README.md
- client/src/components/RelatedProducts.jsx
- client/src/index.jsx
1. Updated badges
2. Update install instructions
> update: updated README.md

- client/src/components/Rat&Rev/Ratings.jsx
- client/src/components/Rat&Rev/ReviewTile.jsx
- client/src/components/Rat&Rev/Reviews.jsx
- client/src/components/RatingsAndReviews.jsx
> add: Ratings+Reviews skeleton

- client/src/components/App.css
- client/src/components/App.jsx
- client/src/components/Overview.jsx
- client/src/components/Overview/AddToCart.jsx
- client/src/components/Overview/Announcement.jsx
- client/src/components/Overview/ImageGallery.css
- client/src/components/Overview/ImageGallery.jsx
- client/src/components/Overview/ProductInformation.css
- client/src/components/Overview/ProductInformation.jsx
- client/src/components/Overview/Search.css
- client/src/components/Overview/Search.jsx
- client/src/components/Overview/StyleSelector.jsx
- client/src/components/QandA.jsx
- client/src/components/Rat&Rev/ReviewTile.jsx
- client/src/components/RatingsAndReviews.jsx
- client/src/components/RelatedProducts.jsx
- client/src/components/shared/Stars.jsx
- package.json
- webpack.config.js
1. Added css-loader for webpack to allow component-styling
2. Added styles-loader for webpack to allow component-styling
1. A new .css file for App.js and our major components
1. imported App.css
1. New rules in module allow for utilizing component styling
- This will present our logo and search bar
- Presents the main image
- Has semi-working buttons
- Presents product information
- Just an outline at this time
> Overview skeleton

- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- tests/initial.test.js
added: Answer Component
added: Modal Components Templates
> QuestionList and Answers

- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
implemented single card in Card.jsx
connected related products details pulled from get request on products styles endpoint
> Card component debut

- client/src/components/QandA.jsx
- jest.config.js
- package.json
- tests/initial.test.js
- Removed comment mentioning broken test
- Added file to hold configuration for jest 
- Currently only contains exceptions for css modules
- importing jest-css-module to resolve css module issues
- Reverted back to previous changes for testing.
- This is still only a template for future testing.
> Jest css fix

- client/src/components/Overview/ProductInformation.css
- client/src/components/Overview/ProductInformation.jsx
- client/src/components/shared/Common.css
- client/src/components/shared/Star.jsx
- client/src/components/shared/Stars.jsx
- package.json
Added Stars component. 
Currently only displays 5 outlined stars
Added favicon to dev environment.
Stars component is still incomplete, but framework is there to start.
> Stars Component

- client/src/components/App.css
- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/Carousel.jsx
- client/src/components/RelatedProductsSubFolder/OutfitList.jsx
- client/src/components/RelatedProductsSubFolder/RelPro.css
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
implemented basic css for Related-Products
modified the card layout in card.jsx
>  created and updated rel-prod css file

- client/src/components/App.css
- client/src/components/App.jsx
- client/src/components/Overview.jsx
- client/src/components/Overview/Overview.css
- client/src/components/Overview/ProductInformation.jsx
- client/src/components/Overview/StyleSelector.jsx
Anything with a .css ending was styling changes 
App.jsx - Minor linting changes 
Overview.jsx - Implemented a "currentStyle" state 
ProductInformation.jsx - Implemented the StyleSelector component 
StyleSelector.jsx - Displays and allows a user to select from up to 8 styles at a time.
> add: style selector functionality and css

- client/src/components/App.jsx
- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/QandA.css
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
added: styles for Q and A
fixed: conditional rendering for the load more answers
> Initial styling

- client/src/components/Overview/Overview.css
change cursors to pointers when hovering over buttons.
> add: pointer cursor over buttons

- client/src/components/App.css
- client/src/components/Overview/Overview.css
- tests/search.test.js
- Just a test to verify that the Announcement component renders.
> add: announcement test

- client/src/components/RelatedProducts.jsx
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
- tests/initial.test.js
> First react component test

- .eslintignore
- .eslintrc.js
- client/src/components/App.jsx
- client/src/components/Overview/Announcement.jsx
- client/src/components/Overview/ImageGallery.jsx
- client/src/components/Overview/ProductInformation.jsx
- client/src/components/Overview/Search.jsx
- client/src/components/Overview/StyleSelector.jsx
- client/src/components/Overview/VerticalCarousel.jsx
- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- client/src/components/QandASubFolder/SearchQuestions.jsx
- client/src/components/Rat&Rev/Ratings.jsx
- client/src/components/Rat&Rev/ReviewTile.jsx
- client/src/components/Rat&Rev/Reviews.jsx
- client/src/components/RatingsAndReviews.jsx
- client/src/components/RelatedProducts.jsx
- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/Carousel.jsx
- client/src/components/RelatedProductsSubFolder/OutfitList.jsx
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
- client/src/components/shared/Star.jsx
- client/src/components/shared/Stars.jsx
- client/src/index.jsx
- package.json
Please check all of YOUR components for changes. 
There were minor linting changes in almost all files. 
.eslintrc.js was adjusted to incorporate plugins properly 
package.json was adjusted to remove airbnb-base and replace it with airbnb 
Leave comments on any changes that you don't understand within your area of responsibility. 
This request should NOT be merged until all team members have commented that they approve these changes.
> Massive Linter Overhaul!

- client/src/components/App.jsx
- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Modal.css
- client/src/components/QandASubFolder/QandA.css
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
> Modal render

- client/src/components/App.css
- client/src/components/App.jsx
- client/src/components/Overview.jsx
- client/src/components/Overview/Overview.css
- client/src/components/Overview/StyleSelector.jsx
- client/src/components/Overview/VerticalCarousel.jsx
Fixed hero image from bleeding over into rest of page. 
Fixed issues where unique keys were not generated for Vertical Carousel.
Fixed issues where vertical carousel images were not properly sized.
> Overview CSS Fixes

- client/src/components/App.jsx
- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Modal.css
- client/src/components/QandASubFolder/QandA.css
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- tests/initial.test.js
Modal Refactor
added: window to add photos
fixed: rerender modals further down the component tree
added: styling to modals
added: grabbing product info on App component
> Styling modals

- client/src/components/App.jsx
- client/src/components/RelatedProducts.jsx
- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/Carousel.jsx
- client/src/components/RelatedProductsSubFolder/ComparingModal.jsx
- client/src/components/RelatedProductsSubFolder/RelPro.css
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
1. change modal rendering to use {name: 'modal_name'}
2. moved modalStatus state around rel_Pro subfolder as needed .
3. structured comparing modal component.
4. updated some relPro #Css
> Rel pro modal

- client/src/components/App.css
- client/src/components/App.jsx
- client/src/components/QandA.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- tests/initial.test.js
added: ability to add up to 5 photos based on URLs in new answer modal
fixed: "Seller" answers appear first
added: use regex to test for valid email
added: sent warnings for empty necessary form fields in modal
added: new font to entire app (Arial)
fixed: subtitle for new question modal is properly formatted
> Photo form

- client/src/components/Overview.jsx
- client/src/components/Overview/AddToCart.jsx
- client/src/components/Overview/ImageGallery.jsx
- client/src/components/Overview/ProductInformation.jsx
- client/src/components/Overview/StyleSelector.jsx
- tests/Overview/addToCart.test.js
- tests/Overview/imageGallery.test.js
- tests/Overview/overview.test.js
- tests/Overview/productInfo.test.js
- webpack.config.js
- Added data-testid for easier targeting during testing
- Added testing to ensure that components render 
- Added minor functionality testing
- Removed unnecessary comments
- Fixed bug where selecting a new style after selecting quantity caused error 
- Fixed by moving currentSku state up to ProductInformation.jsx
> Overview tests

- client/src/components/App.jsx
- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- tests/QandA/answer.test.js
- tests/QandA/question.test.js
- tests/QandA/questionsList.test.js
added: tests for Questions
added: tests for Answers
fixed: cleaned up App.jsx
changed: conditional rendering throughout
> Q and A tests

- client/src/components/QandASubFolder/AddAnswerModal.jsx
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/AnswerForm.jsx
- client/src/components/QandASubFolder/PhotoForm.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionFooter.jsx
- client/src/components/QandASubFolder/QuestionHeader.jsx
- client/src/lib/helpers.js
closes #58, #57, #60, #59 
fixed: refactored modals into smaller subcomponents
fixed: removed comments
fixed: refactored Question into smaller subcomponents
fixed: moved date function to lib/helpers.js
> Closes Q and A issues

- client/src/components/App.css
- client/src/components/App.jsx
- client/src/components/RelatedProducts.jsx
- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/Carousel.jsx
- client/src/components/RelatedProductsSubFolder/ComparingModal.jsx
- client/src/components/RelatedProductsSubFolder/RelPro.css
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
made an APi call to get each product ratings in card.jsx
adjusted Css to fit the stars (ratings) on each card
deleted unused props.
> Products ratings

- client/dist/index.html
- client/src/components/Overview/AddToCart.jsx
- client/src/components/Overview/ImageGallery.jsx
- client/src/components/Overview/Overview.css
- client/src/components/Overview/Search.jsx
- client/src/components/Overview/VerticalCarousel.jsx
- client/src/components/QandASubFolder/QandA.css
- client/src/components/RelatedProducts.jsx
- added aria-labels to buttons for screen readers
- added contrast to search input to ensure better accessibility
> Accessibility seo improvements

- client/src/components/Overview/ProductInformation.jsx
fixes the issue mention in title
> fix: addresses bug where sizes couldnt select on page load

- client/dist/main.js.LICENSE.txt
- client/src/components/QandASubFolder/Answer.jsx
- client/src/components/QandASubFolder/Question.jsx
- client/src/components/QandASubFolder/QuestionsList.jsx
- package.json
- webpack.config.js
added: ability to infinite scroll Questions
fixed: reduced api calls and now widget only does one and handles sort
> Infinite scroll

- client/src/components/App.jsx
- client/src/components/RelatedProducts.jsx
- client/src/components/RelatedProductsSubFolder/Card.jsx
- client/src/components/RelatedProductsSubFolder/Carousel.jsx
- client/src/components/RelatedProductsSubFolder/OutfitList.jsx
- client/src/components/RelatedProductsSubFolder/RelPro.css
- client/src/components/RelatedProductsSubFolder/RelatedProductsList.jsx
- tests/RelatedProducts/card.test.js
- tests/RelatedProducts/carousel.test.js
- tests/RelatedProducts/outFit.test.js
- tests/RelatedProducts/relatedProducts.test.js
- tests/RelatedProducts/relatedProductsList.test.js
Added new test Files
Wrote more RElated Products tests.
> Rel pro testing

- client/src/components/QandASubFolder/AddQuestionModal.jsx
- client/src/components/QandASubFolder/AnswerForm.jsx
- client/src/components/QandASubFolder/Modal.css
> cleaned up modal design

- client/src/components/QandASubFolder/QuestionsList.jsx
- package.json
- tests/QandA/questionsList.test.js
fixed: scroll built from scratch
fixed: uninstalled infinite-scroll module
fixed: removed comments
fixed: resets number of questions displayed when product changes
> Scroll refactor
